[package]
name = "axii_proxy"
version = "0.1.0"
edition = "2021"

[lib]
name = "dinput8"
crate-type = ["cdylib"]

[dependencies.windows]
version = "0.57.0"
features = [
  "Win32_Security",
  "Win32_System_Threading",
  "Win32_System_LibraryLoader",
  "Win32_System_SystemServices",
]
