[package]
name = "roach"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
windows = { version = "0.58.0", features = ["Win32_System_LibraryLoader"] }
igni = { path = "../igni" }
axii_sdk = { path = "../axii_sdk" }
minhook = "0.5.0"
