[package]
name = "roach"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.windows]
version = "0.58.0"
features = ["Win32_System_LibraryLoader"]

[dependencies.transcend]
version = "0.1.0"
git = "https://github.com/KiraCoding/transcend.git"
